# -*- mode: makefile-gmake; coding: euc-jp-unix -*-
#==============================================================================

VENV_REQUIRE =		\
	flask==0.10.1	\
	tornado==3.1.1

VENV_REQUIRE_DEVEL =		\
	pyreadline==2.0			\
	ipython==1.1.0			\
	nose==1.3.0				\
	logilab-common==0.60.0	\
	logilab-astng==0.24.3	\
	pylint==1.0.0

include ../devel/venv.mk

