# -*- mode: makefile-gmake; coding: euc-jp-unix -*-
#==============================================================================

include ../devel/py2env.mk

REQUIREMENT +=			\
	flask==0.10.1		\
	flask-googleauth	\
	tornado==3.1.1


#------------------------------------------------------------------------------
run-server:
	$(PYTHON) -u server.py

#------------------------------------------------------------------------------
debug-server:
	$(PYTHON) -u app.py

